apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: do0tam6ny-go 
  janus-idp.io/tekton: do0tam6ny-go
  backstage.io/kubernetes-id: do0tam6ny-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: do0tam6ny-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  