apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: do0tam6ny-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: do0tam6ny-go 
  name: do0tam6ny-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: do0tam6ny-go 
